---
abstract: 'testing framework to test Ajax/Javascript libraries'
author:
  - 'Kazuhiro Osawa <yappo <at> shibuya <döt> pl>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JSTAPd
no_index:
  directory:
    - inc
    - share
    - t
    - xt
requires:
  Data::Dumper: 0
  Data::UUID: 0
  File::ShareDir: 0
  FindBin: 0
  Getopt::Long: 0
  HTTP::Request: 0
  JSON::XS: 0
  LWP::UserAgent: 0
  Path::Class: 0
  Plack: 0
  Pod::Usage: 0
  Test::TCP: 0
  Time::HiRes: 0
  Twiggy: 0
resources:
  homepage: https://github.com/yappo/JSTAPd/tree
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/yappo/JSTAPd.git
    web: https://github.com/yappo/JSTAPd/tree
version: 0.03
