---
abstract: 'testing framework to test Ajax/Javascript libraries'
author:
  - 'Kazuhiro Osawa <yappo <at> shibuya <döt> pl>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JSTAPd
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Data::Dumper: 0
  Data::UUID: 0
  FindBin: 0
  Getopt::Long: 0
  HTTP::Engine: 0
  HTTP::Request: 0
  JSON::XS: 0
  LWP::UserAgent: 0
  Path::Class: 0
  Test::TCP: 0
  Time::HiRes: 0
resources:
  homepage: http://github.com/yappo/JSTAPd/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/yappo/JSTAPd.git
version: 0.01
